import type { ActionTimelineEntry, DiagnosticEventRow } from '@open-codesign/shared';
import { describe, expect, it } from 'vitest';
import { type SummaryInput, composeSummaryMarkdown } from './diagnostic-summary';

function baseEvent(overrides: Partial<DiagnosticEventRow> = {}): DiagnosticEventRow {
  return {
    id: 1,
    schemaVersion: 1,
    ts: Date.UTC(2026, 0, 1, 12, 0, 0),
    level: 'error',
    code: 'E_PROVIDER_TIMEOUT',
    scope: 'provider',
    runId: 'run-abc',
    fingerprint: 'deadbeef',
    message: 'Request timed out',
    stack: undefined,
    transient: false,
    count: 3,
    context: undefined,
    ...overrides,
  };
}

function baseInput(overrides: Partial<SummaryInput> = {}): SummaryInput {
  return {
    event: baseEvent(),
    appVersion: '0.4.0',
    platform: 'darwin-arm64',
    electronVersion: '33.2.1',
    nodeVersion: '22.11.0',
    timeline: [],
    recentLogTail: ['[00:00] hello', '[00:01] world'],
    notes: '',
    includePromptText: true,
    includePaths: true,
    includeUrls: true,
    includeTimeline: true,
    ...overrides,
  };
}

describe('composeSummaryMarkdown', () => {
  it('renders header, environment, and "(no stack)" when stack is undefined', () => {
    const md = composeSummaryMarkdown(baseInput());
    expect(md).toContain('# Diagnostic Report — E_PROVIDER_TIMEOUT');
    expect(md).toContain('**Fingerprint:** `deadbeef`  (seen 3 times)');
    expect(md).toContain('**Run id:** `run-abc`');
    expect(md).toContain('- App: 0.4.0');
    expect(md).toContain('- Electron: 33.2.1 / Node: 22.11.0');
    expect(md).toContain('### Stack (top 5 frames)');
    expect(md).toContain('(no stack)');
    expect(md).toContain('(none)');
    expect(md).toContain('Generated by open-codesign 0.4.0.');
  });

  it('renders top 5 frames normalized from a real stack', () => {
    const stack = [
      'Error: boom',
      '    at generate (/Users/alice/code/pkg/src/index.ts:482:11)',
      '    at Object.submit (/Users/alice/code/pkg/src/submit.ts:10:3)',
      '    at step (/Users/alice/code/pkg/src/step.ts:1:1)',
      '    at a (/x/a.ts:1:1)',
      '    at b (/x/b.ts:1:1)',
      '    at c (/x/c.ts:1:1)',
      '    at d (/x/d.ts:1:1)',
    ].join('\n');
    const md = composeSummaryMarkdown(baseInput({ event: baseEvent({ stack }) }));
    expect(md).toContain('at generate (index.ts)');
    expect(md).toContain('at Object.submit (submit.ts)');
    expect(md).toContain('at step (step.ts)');
    expect(md).toContain('at a (a.ts)');
    expect(md).toContain('at b (b.ts)');
    expect(md).not.toContain('at c (c.ts)');
  });

  it('renders timeline as a table with relative-second offsets newest-first', () => {
    const eventTs = Date.UTC(2026, 0, 1, 12, 0, 0);
    const timeline: ActionTimelineEntry[] = [
      { ts: eventTs - 42_000, type: 'prompt.submit', data: { promptLen: 312 } },
      { ts: eventTs - 12_000, type: 'prompt.cancel' },
      { ts: eventTs - 30_000, type: 'provider.switch', data: { to: 'anthropic' } },
    ];
    const md = composeSummaryMarkdown(baseInput({ event: baseEvent({ ts: eventTs }), timeline }));
    expect(md).toContain('| Offset | Type | Details |');
    const tableStart = md.indexOf('| -12 s |');
    const middle = md.indexOf('| -30 s |');
    const last = md.indexOf('| -42 s |');
    expect(tableStart).toBeGreaterThan(-1);
    expect(tableStart).toBeLessThan(middle);
    expect(middle).toBeLessThan(last);
    expect(md).toContain('promptLen=312');
    expect(md).toContain('| -12 s | prompt.cancel | — |');
  });

  it('omits timeline when includeTimeline is false', () => {
    const md = composeSummaryMarkdown(baseInput({ includeTimeline: false }));
    expect(md).toContain('_(timeline omitted — user chose not to include)_');
    expect(md).not.toContain('| Offset | Type |');
  });

  it('renders upstream context for provider scope with all 4 fields', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        event: baseEvent({
          scope: 'provider',
          context: {
            upstream_provider: 'anthropic',
            upstream_status: 504,
            upstream_request_id: 'req_123',
            retry_count: 2,
            redacted_body_head: '{"type":"error","message":"timeout"}',
          },
        }),
      }),
    );
    expect(md).toContain('### Upstream context');
    expect(md).toContain('- Provider: anthropic');
    expect(md).toContain('- Status: 504');
    expect(md).toContain('- Request-Id: req_123');
    expect(md).toContain('- Retry count: 2');
    expect(md).toContain('- Body head: {"type":"error","message":"timeout"}');
  });

  it('does not render upstream context for non-provider scope', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        event: baseEvent({
          scope: 'ipc',
          context: { upstream_provider: 'anthropic' },
        }),
      }),
    );
    expect(md).not.toContain('### Upstream context');
  });

  it('redacts paths and URLs when includePaths/includeUrls are false', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        event: baseEvent({
          message: 'Failed at /Users/alice/foo/bar.ts see https://example.com/x',
        }),
        recentLogTail: ['/Users/alice/app.log https://example.com/y'],
        includePaths: false,
        includeUrls: false,
      }),
    );
    expect(md).not.toContain('/Users/alice');
    expect(md).not.toContain('https://example.com');
    expect(md).toContain('<path omitted>');
    expect(md).toContain('<url omitted>');
  });

  it('redacts prompt-looking message when includePromptText is false', () => {
    const longPrompt = `You are a helpful assistant.\n\n${'x'.repeat(250)}\n\n请帮我写代码`;
    const md = composeSummaryMarkdown(
      baseInput({
        event: baseEvent({ message: longPrompt }),
        includePromptText: false,
      }),
    );
    expect(md).toContain('<prompt omitted>');
    expect(md).not.toContain('x'.repeat(250));
  });

  it('caps output at 20 KB with a truncation suffix', () => {
    const huge = 'a'.repeat(50_000);
    const md = composeSummaryMarkdown(baseInput({ notes: huge }));
    expect(new TextEncoder().encode(md).byteLength).toBeLessThanOrEqual(20 * 1024);
    expect(md).toMatch(/_\(summary truncated to 20 KB — full bundle attached as zip\)_$/);
  });

  it('renders "(none)" for blank or whitespace-only notes', () => {
    const md = composeSummaryMarkdown(baseInput({ notes: '   \n  ' }));
    expect(md).toContain('## Reporter notes\n(none)');
  });
});
